In [14]:
import math;

In [15]:
a=int(input("donner a:"))

donner a: 5


In [16]:
b=int(input("donner b:"))

donner b: 7


In [17]:
c=int(input("donner c:"))


donner c: 1


In [19]:
if(a==0):
    if(b==0):
        if(c==0):
            print("sol R")
        else:
            print("pas de sol dans R")
    else:
        print("sol",-c/b)
else:
    delta=((b*b)-(4*a*c))
    if (delta<0):
        print("pas de sol dans R")
    if(delta==0):
        print("sol double :",-b/(2*a))
    if(delta>0):
        x1=(-b-math.sqrt(delta))/(2*a)
        x2=(-b+math.sqrt(delta))/(2*a)
        print("2 sol",x1,x2)

2 sol -1.2385164807134506 -0.16148351928654964


In [28]:
#ex2
import numpy as np;    

In [29]:
revenues=np.array([1,5,4,8])
#revenues=np.array(lst) lst=[1,5,4,8]

In [30]:
def averge(lst):
    return(sum(lst)/len(lst))
print (averge(revenues))

4.5


In [31]:
print(revenues.mean());

4.5


In [32]:
np.mean(revenues)

4.5

In [34]:
np.argmax(revenues)

3

In [35]:
np.sort(revenues)

array([1, 4, 5, 8])

In [36]:
revenues[:3]

array([1, 5, 4])

In [47]:
revenues[::2]

array([1, 4])

In [50]:
revenues[revenues >200 ]

array([], dtype=int32)

In [53]:
import random ;
tab=np.random.randint(1,11,size=(2,2))

In [54]:
print(tab)

[[2 3]
 [8 5]]


In [55]:
tab[0]

array([2, 3])

In [65]:
t=[1,2,3]
#t2=np.r_[tab,t]
t2=np.vstack([tab,t[:2]])

In [67]:
t1=np.delete(tab,1,axis=0)

In [69]:
print (t1)

[[2 3]]


In [70]:
#ex3
import pandas as pd

In [80]:
data={"state":["tunis","bizerte","sfax","sousse","gabes"],"year":["2000","2001","2002","2001","2002"],"pop":["1.5","1.7","3.6","2.4","2.9"]}

In [85]:
df=pd.DataFrame(data)

In [86]:
df.info

<bound method DataFrame.info of      state  year  pop
0    tunis  2000  1.5
1  bizerte  2001  1.7
2     sfax  2002  3.6
3   sousse  2001  2.4
4    gabes  2002  2.9>

In [96]:
print(df)#afficher comme tableau

      B    C       D
0  2000  5.5    nord
1  2001  5.5  centre
2  2002  5.5     sud
3  2001  5.5    nord
4  2002  5.5  centre


In [88]:
print(df.columns)

Index(['state', 'year', 'pop'], dtype='object')


In [90]:
df["pop"]=5.5
print(df)

     state  year  pop
0    tunis  2000  5.5
1  bizerte  2001  5.5
2     sfax  2002  5.5
3   sousse  2001  5.5
4    gabes  2002  5.5


In [93]:
df["zone"]=["nord","centre","sud","nord","centre"]
print(df)

     state  year  pop    zone
0    tunis  2000  5.5    nord
1  bizerte  2001  5.5  centre
2     sfax  2002  5.5     sud
3   sousse  2001  5.5    nord
4    gabes  2002  5.5  centre


In [94]:
df.columns=["A","B","C","D"]
print(df)

         A     B    C       D
0    tunis  2000  5.5    nord
1  bizerte  2001  5.5  centre
2     sfax  2002  5.5     sud
3   sousse  2001  5.5    nord
4    gabes  2002  5.5  centre


In [95]:
df=df.drop(columns=["A"])
print(df)

      B    C       D
0  2000  5.5    nord
1  2001  5.5  centre
2  2002  5.5     sud
3  2001  5.5    nord
4  2002  5.5  centre


In [98]:
#ex4
df=pd.read_csv("pima-indians-diabetes.data.csv")

In [102]:
df.columns=["NumTimesPrg","PlGlcConc","BloodP","SkinThick","TwoHourSerIns","BMI","DiPedFunc","age","HasDiabetes"]

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   NumTimesPrg    767 non-null    int64  
 1   PlGlcConc      767 non-null    int64  
 2   BloodP         767 non-null    int64  
 3   SkinThick      767 non-null    int64  
 4   TwoHourSerIns  767 non-null    int64  
 5   BMI            767 non-null    float64
 6   DiPedFunc      767 non-null    float64
 7   age            767 non-null    int64  
 8   HasDiabetes    767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [104]:
df.head(10)

NumTimesPrg  PlGlcConc  BloodP  SkinThick  TwoHourSerIns   BMI  DiPedFunc  \
0            1         85      66         29              0  26.6      0.351   
1            8        183      64          0              0  23.3      0.672   
2            1         89      66         23             94  28.1      0.167   
3            0        137      40         35            168  43.1      2.288   
4            5        116      74          0              0  25.6      0.201   
5            3         78      50         32             88  31.0      0.248   
6           10        115       0          0              0  35.3      0.134   
7            2        197      70         45            543  30.5      0.158   
8            8        125      96          0              0   0.0      0.232   
9            4        110      92          0              0  37.6      0.191   

   age  HasDiabetes  
0   31            0  
1   32            1  
2   21            0  
3   33            1  
4   30            0  
5   26            1  
6   29            0  
7   53            1  
8   54            1  
9   30            0

In [105]:
df["BloodP"]

0      66
1      64
2      66
3      40
4      74
       ..
762    76
763    70
764    72
765    60
766    70
Name: BloodP, Length: 767, dtype: int64

In [106]:
df.describe()

NumTimesPrg   PlGlcConc      BloodP   SkinThick  TwoHourSerIns  \
count   767.000000  767.000000  767.000000  767.000000     767.000000   
mean      3.842243  120.859192   69.101695   20.517601      79.903520   
std       3.370877   31.978468   19.368155   15.954059     115.283105   
min       0.000000    0.000000    0.000000    0.000000       0.000000   
25%       1.000000   99.000000   62.000000    0.000000       0.000000   
50%       3.000000  117.000000   72.000000   23.000000      32.000000   
75%       6.000000  140.000000   80.000000   32.000000     127.500000   
max      17.000000  199.000000  122.000000   99.000000     846.000000   

              BMI   DiPedFunc         age  HasDiabetes  
count  767.000000  767.000000  767.000000   767.000000  
mean    31.990482    0.471674   33.219035     0.348110  
std      7.889091    0.331497   11.752296     0.476682  
min      0.000000    0.078000   21.000000     0.000000  
25%     27.300000    0.243500   24.000000     0.000000  
50%     32.000000    0.371000   29.000000     0.000000  
75%     36.600000    0.625000   41.000000     1.000000  
max     67.100000    2.420000   81.000000     1.000000

In [107]:
X=df.drop(columns=["HasDiabetes"]).values

In [108]:
Y=df["HasDiabetes"].values

In [109]:
print (X[:10])

[[1.000e+00 8.500e+01 6.600e+01 2.900e+01 0.000e+00 2.660e+01 3.510e-01
  3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01
  3.200e+01]
 [1.000e+00 8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01
  2.100e+01]
 [0.000e+00 1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00
  3.300e+01]
 [5.000e+00 1.160e+02 7.400e+01 0.000e+00 0.000e+00 2.560e+01 2.010e-01
  3.000e+01]
 [3.000e+00 7.800e+01 5.000e+01 3.200e+01 8.800e+01 3.100e+01 2.480e-01
  2.600e+01]
 [1.000e+01 1.150e+02 0.000e+00 0.000e+00 0.000e+00 3.530e+01 1.340e-01
  2.900e+01]
 [2.000e+00 1.970e+02 7.000e+01 4.500e+01 5.430e+02 3.050e+01 1.580e-01
  5.300e+01]
 [8.000e+00 1.250e+02 9.600e+01 0.000e+00 0.000e+00 0.000e+00 2.320e-01
  5.400e+01]
 [4.000e+00 1.100e+02 9.200e+01 0.000e+00 0.000e+00 3.760e+01 1.910e-01
  3.000e+01]]


In [110]:
print (Y[:10])

[0 1 0 1 0 1 0 1 1 0]
